---
  - hosts: webservers:loadbalancers
    become: true
    tasks:
      - name: Check apache status
        command: service httpd status
        args:
          warn: no
        changed_when: false

      - name: This is not fail
        command: /bin/false
        ignore_errors: yes
